## Import and Install

In [1]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/tf_env/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
dataset = pd.read_csv('salaries.csv')
pd.DataFrame(dataset.head())

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025,EX,FT,Head of Data,348516,USD,348516,US,0,US,M
1,2025,EX,FT,Head of Data,232344,USD,232344,US,0,US,M
2,2025,SE,FT,Data Scientist,145400,USD,145400,US,0,US,M
3,2025,SE,FT,Data Scientist,81600,USD,81600,US,0,US,M
4,2025,MI,FT,Engineer,160000,USD,160000,US,100,US,M

## Cleaning Dataset

In [6]:
# clean empty data 
new_dataset = dataset.dropna()

# check duplicates
print(new_dataset.duplicated().sum())

79532

In [7]:
# delete duplicates
new_dataset.drop_duplicates(inplace=True)
print(new_dataset.duplicated().sum())

0

In [8]:
new_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71913 entries, 0 to 151444
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           71913 non-null  int64
 1   experience_level    71913 non-null  object
 2   employment_type     71913 non-null  object
 3   job_title           71913 non-null  object
 4   salary              71913 non-null  int64
 5   salary_currency     71913 non-null  object
 6   salary_in_usd       71913 non-null  int64
 7   employee_residence  71913 non-null  object
 8   remote_ratio        71913 non-null  int64
 9   company_location    71913 non-null  object
 10  company_size        71913 non-null  object
dtypes: int64(4), object(7)
memory usage: 6.6+ MB

In [9]:
# buang column yang tidak dipakai 
dataset_final = new_dataset.drop(columns=['salary_currency', 'salary'])
dataset_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 71913 entries, 0 to 151444
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           71913 non-null  int64
 1   experience_level    71913 non-null  object
 2   employment_type     71913 non-null  object
 3   job_title           71913 non-null  object
 4   salary_in_usd       71913 non-null  int64
 5   employee_residence  71913 non-null  object
 6   remote_ratio        71913 non-null  int64
 7   company_location    71913 non-null  object
 8   company_size        71913 non-null  object
dtypes: int64(3), object(6)
memory usage: 5.5+ MB

In [17]:
# target 
y = dataset_final.salary_in_usd

# features 
salary_features = [
    'work_year', 'experience_level', 'employment_type', 
    'job_title', 'employee_residence',
    'remote_ratio', 'company_location', 'company_size'
]
X = dataset_final[salary_features]

# diganti menjadi angka 
X = pd.get_dummies(X)

# EN: Entry-level / Junior
# MI: Mid-level / Intermediate
# SE: Senior-level
# EX: Executive / Director

# FT: Full-time
# PT: Part-time
# CT: Contract
# FL: Freelance

# S: Small (1–50 employees)
# M: Medium (51–500 employees)
# L: Large (501+ employees)

X.head()

,work_year,remote_ratio,experience_level_EN,experience_level_EX,experience_level_MI,experience_level_SE,employment_type_CT,employment_type_FL,employment_type_FT,employment_type_PT,...,company_location_UA,company_location_US,company_location_VE,company_location_VN,company_location_XK,company_location_ZA,company_location_ZM,company_size_L,company_size_M,company_size_S
0,2025,0,False,True,False,False,False,False,True,False,...,False,True,False,False,False,False,False,False,True,False
1,2025,0,False,True,False,False,False,False,True,False,...,False,True,False,False,False,False,False,False,True,False
2,2025,0,False,False,False,True,False,False,True,False,...,False,True,False,False,False,False,False,False,True,False
3,2025,0,False,False,False,True,False,False,True,False,...,False,True,False,False,False,False,False,False,True,False
4,2025,100,False,False,True,False,False,False,True,False,...,False,True,False,False,False,False,False,False,True,False